spring.application.name=reservas-api

spring.datasource.url=jdbc:postgresql://localhost:5432/reservas_db
spring.datasource.username=reservas_user
spring.datasource.password=reservas_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=a21235s4df4eg8w16asd48as4c4v8w4fdq89da/s*dwd8qc11wda5as8d7/fv4a1c6ca8s43qw*as/d4a51d5wa/*c-+4a81sc
jwt.expiration-ms=86400000